strict: true

analyzer_rules:
  - all

opt_in_rules:
  - all

disabled_rules:
  - accessibility_label_for_image
  - closure_body_length
  - conditional_returns_on_newline
  - contrasted_opening_brace
  - explicit_acl
  - explicit_top_level_acl
  - explicit_type_interface
  - force_unwrapping
  - function_body_length
  - indentation_width
  - multiple_closures_with_trailing_closure
  - no_magic_numbers
  - opening_brace
  - required_deinit
  - trailing_comma
  - type_contents_order

